const express = require('express')
const xss = require('xss-clean')
const hpp = require('hpp')
const dotenv = require('dotenv')
dotenv.config({ path: '/.env' })

const accountRoute=require('./routes/accountRoute')
const authorRoute=require('./routes/authorRoute')
const bookAuthorRoute=require('./routes/bookAuthorRoute')
const bookGenreRoute=require('./routes/bookGenreRoute')
const bookRoute=require('./routes/bookRoute')
const genreRoute=require('./routes/genreRoute')
const paymentRoute=require('./routes/paymentRoute')
const subscriptionRoute=require('./routes/subscriptionRoute')
const subscriptionHistoryRoute=require('./routes/subscriptionHistoryRoute')
const bookProgressRoute=require('./routes/bookProgressRoute')
const userRoute=require('./routes/userRoute')
const favoriteRoute=require('./routes/favoriteRoute')

const port = process.env.PORT || 5000
const app = express()
app.get('/', (req, res) => {
  res.send('Hello World!')
})
app.use(express.json({ limit: '10mb' }))
app.use('/api/v1/user', userRoute)
app.use('/api/v1/account', accountRoute)
app.use('/api/v1/author', authorRoute)
app.use('/api/v1/bookAuthor', bookAuthorRoute)
app.use('/api/v1/bookGenre', bookGenreRoute)
app.use('/api/v1/book', bookRoute)
app.use('/api/v1/genre', genreRoute)
app.use('/api/v1/payment', paymentRoute)
app.use('/api/v1/subscription', subscriptionRoute)
app.use('/api/v1/subscriptionHistory', subscriptionHistoryRoute)
app.use('/api/v1/bookProgress', bookProgressRoute)
app.use('/api/v1/favorite',favoriteRoute)

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
